default:
    dsn_omop                      : "cdw_omop_1"

    directory_codeset_input       : "concept-sets/input"
    directory_codeset_output      : "concept-sets"
    directory_codeset_output_try1      : "concept-sets/try-1.json"

    # Central Database (a cache of the OMOP concept table).
    path_database:            "data-unshared/db.sqlite3"

    path_log_flow:            !expr strftime(Sys.time(), "data-unshared/log/%Y/%Y-%m/flow-%Y-%m-%d--%H-%M-%S.log")
