default:

    directory_codeset_input       : "concept-sets/input"


    # # Central Database (produced by Ellis lanes).
    # path_database:            "data-public/derived/db.sqlite3"

    path_log_flow:            !expr strftime(Sys.time(), "data-unshared/log/%Y/%Y-%m/flow-%Y-%m-%d--%H-%M-%S.log")
